# Generated by Django 3.1.7 on 2021-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('cash_balance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurant_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestTimingss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField()),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rest_timingss',
                'managed': False,
            },
        ),
    ]
